# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  20202021backendlabo09ai:
    image: 20202021backendlabo09ai
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
